- name: Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Copy expense config file
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Remove old nginx content
      ansible.builtin.file:
        path: /use/share/nginx/html
        state: absent

    - name: Create Nginx Directory
      ansible.builtin.file:
        path: /use/share/nginx/html
        state: directory

    - name: Download and Extract Frontend code
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /use/share/nginx/html
        remote_src: yes

    - name: Restart Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
