- name: Mysql Setup
  hosts: all
  become: yes
  tasks:
    - name: Placing MySQL repo file
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Disabling Mysql 8
      ansible.builtin.shell: dnf module disable mysql -y

    - name: Installing MySQL server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: Starting MySQL server
      ansible.builtin.systemd:
        name: mysqld
        state: restarted

    - name: Setting root Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1