- name: Verify NodeJS
  ansible.builtin.shell: type npm
  register: npm
  ignore_errors: yes

- name: Install NodeJS repo file
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  when: npm.rc != 0

- name: Installing NodeJS
  ansible.builtin.dnf:
    name: nodejs
  when: npm.rc != 0

- name: Copying backend.service file
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Adding Application user
  ansible.builtin.user:
    name: expense

- name: Removing old App content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and Extract Backend code
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/backend.zip
    dest: /app
    remote_src: yes

- name: Install Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Restart Backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes

- name: Installing MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql.yamunadevops.online -uroot -pExpenseApp@1 < /app/schema/backend.sql